name: Context Output
on: push

jobs:
  dump_contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github context
        id: github-context-step
        run: echo '${{ toJson(github) }}'
      - name: Dump job Context
        run: echo '${{ toJson(job) }}'
      - name: Dump steps context
        run: echo '${{ toJson(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJson(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJson(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJson(matrix) }}'
